### ISSUE TITLE
Can I use the data and figure in a Q&A forum?

### ISSUE THREAD

**Issue by xiezhq-hermann** [przemyslaw-pawelczak/ASPLOS_2020_Activity_Stats#1]
Hi Przemysław, the statistics and visualization you made are really inspiring for me. I'd like to write something about ASPLOS 2020 in a Chinese forum, and I want to use your data to demonstrate some information.
BTW, as far as you know, is there any more statistical data and visualization about ASPLOS 2020 accessible? Many thanks!

**Comment by przemyslaw-pawelczak** [comment]
Hi @xiezhq-hermann Glad you like the data. Of course - feel free to use this information (can you send me the link to the post once its available)?

As for other information, take a look into https://asplos2020.slack.com/stats Also, you can count how many twitter mentions of #asplos or #asplos2020 or #asplos20 were there. For slack, you can inspect what __types__ of messages were sent in each channel (I aggregated everything into a single stream, but some messages are "thank you" notes or pinned links to videos, which would reduce the amount of posts per channel down). You can also inspect who was the most active user in all channels and how many posts to links to dedicated video conferencing (like zoom) were present per channel.
